<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class d_example_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table(env('TABLE_PREFIX').'d_example')->insert([
            [
                "first_name" => "Nanni",
                "last_name" => "Lynes",
                "username" => "nlynes0",
                "email" => "nlynes0@yahoo.co.jp",
                "phone" => "+1-691-218-3394",
                "gender" => "Female",
                "address" => "694 Sugar Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Nanni Lynes",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Pat",
                "last_name" => "Radenhurst",
                "username" => "pradenhurst1",
                "email" => "pradenhurst1@so-net.ne.jp",
                "phone" => "+58-926-809-5716",
                "gender" => "Male",
                "address" => "090 Vahlen Point",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Pat Radenhurst",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Angela",
                "last_name" => "Baterip",
                "username" => "abaterip2",
                "email" => "abaterip2@usgs.gov",
                "phone" => "+420-898-598-7704",
                "gender" => "Female",
                "address" => "3682 Warrior Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Angela Baterip",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Phillipe",
                "last_name" => "Cottrill",
                "username" => "pcottrill3",
                "email" => "pcottrill3@jugem.jp",
                "phone" => "+86-561-296-8419",
                "gender" => "Male",
                "address" => "0 Maywood Trail",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Phillipe Cottrill",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Gage",
                "last_name" => "Sollas",
                "username" => "gsollas4",
                "email" => "gsollas4@ustream.tv",
                "phone" => "+386-524-400-4058",
                "gender" => "Male",
                "address" => "5 Kinsman Drive",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Gage Sollas",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Torrey",
                "last_name" => "Simmens",
                "username" => "tsimmens5",
                "email" => "tsimmens5@1688.com",
                "phone" => "+355-828-202-3886",
                "gender" => "Male",
                "address" => "0993 Dennis Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Torrey Simmens",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Stuart",
                "last_name" => "Rameau",
                "username" => "srameau6",
                "email" => "srameau6@bizjournals.com",
                "phone" => "+48-701-777-0788",
                "gender" => "Male",
                "address" => "5 Browning Road",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Stuart Rameau",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Con",
                "last_name" => "Mawdsley",
                "username" => "cmawdsley7",
                "email" => "cmawdsley7@nifty.com",
                "phone" => "+54-602-563-5287",
                "gender" => "Female",
                "address" => "93268 Carioca Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Con Mawdsley",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Elsy",
                "last_name" => "Palfreman",
                "username" => "epalfreman8",
                "email" => "epalfreman8@trellian.com",
                "phone" => "+374-703-968-4386",
                "gender" => "Female",
                "address" => "6574 Cordelia Lane",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Elsy Palfreman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Tobin",
                "last_name" => "Marler",
                "username" => "tmarler9",
                "email" => "tmarler9@com.com",
                "phone" => "+33-875-451-8253",
                "gender" => "Male",
                "address" => "8244 Hintze Alley",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Tobin Marler",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Correy",
                "last_name" => "MacGilpatrick",
                "username" => "cmacgilpatricka",
                "email" => "cmacgilpatricka@go.com",
                "phone" => "+58-159-205-3285",
                "gender" => "Female",
                "address" => "55 Del Sol Park",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Correy MacGilpatrick",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Billie",
                "last_name" => "Sidney",
                "username" => "bsidneyb",
                "email" => "bsidneyb@tamu.edu",
                "phone" => "+81-528-404-2718",
                "gender" => "Male",
                "address" => "880 Fair Oaks Trail",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Billie Sidney",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Mariska",
                "last_name" => "Esler",
                "username" => "meslerc",
                "email" => "meslerc@rakuten.co.jp",
                "phone" => "+45-765-235-8559",
                "gender" => "Female",
                "address" => "28 Colorado Lane",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Mariska Esler",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Lionello",
                "last_name" => "Fludgate",
                "username" => "lfludgated",
                "email" => "lfludgated@tripod.com",
                "phone" => "+86-486-783-7811",
                "gender" => "Agender",
                "address" => "30 Mayfield Terrace",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/placeatadipiscirepellendus.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Jude",
                "last_name" => "Burgane",
                "username" => "jburganee",
                "email" => "jburganee@slideshare.net",
                "phone" => "+46-575-628-3263",
                "gender" => "Male",
                "address" => "1727 Sommers Point",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Jude Burgane",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Leeanne",
                "last_name" => "McQuorkel",
                "username" => "lmcquorkelf",
                "email" => "lmcquorkelf@sfgate.com",
                "phone" => "+55-538-786-5637",
                "gender" => "Female",
                "address" => "376 Thackeray Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Leeanne McQuorkel",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Lyndy",
                "last_name" => "Crunkhorn",
                "username" => "lcrunkhorng",
                "email" => "lcrunkhorng@booking.com",
                "phone" => "+359-351-316-5401",
                "gender" => "Female",
                "address" => "55 Kim Road",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Lyndy Crunkhorn",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Turner",
                "last_name" => "Stollenhof",
                "username" => "tstollenhofh",
                "email" => "tstollenhofh@posterous.com",
                "phone" => "+880-512-849-3288",
                "gender" => "Male",
                "address" => "11 Waubesa Center",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Turner Stollenhof",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Wain",
                "last_name" => "Tombling",
                "username" => "wtomblingi",
                "email" => "wtomblingi@timesonline.co.uk",
                "phone" => "+62-307-990-8197",
                "gender" => "Male",
                "address" => "86628 Park Meadow Road",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Wain Tombling",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Stephanie",
                "last_name" => "Shewan",
                "username" => "sshewanj",
                "email" => "sshewanj@chicagotribune.com",
                "phone" => "+63-856-240-7848",
                "gender" => "Female",
                "address" => "51312 David Circle",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Stephanie Shewan",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Fredi",
                "last_name" => "Dee",
                "username" => "fdeek",
                "email" => "fdeek@opensource.org",
                "phone" => "+62-290-697-4609",
                "gender" => "Female",
                "address" => "2 Onsgard Drive",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Fredi Dee",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Doria",
                "last_name" => "Menilove",
                "username" => "dmenilovel",
                "email" => "dmenilovel@princeton.edu",
                "phone" => "+256-264-867-2001",
                "gender" => "Non-binary",
                "address" => "26622 Drewry Alley",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/iddelectuspraesentium.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Brittney",
                "last_name" => "Boerderman",
                "username" => "bboerdermanm",
                "email" => "bboerdermanm@mayoclinic.com",
                "phone" => "+380-754-196-2411",
                "gender" => "Female",
                "address" => "388 Hermina Pass",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Brittney Boerderman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Wynn",
                "last_name" => "Sevier",
                "username" => "wseviern",
                "email" => "wseviern@cisco.com",
                "phone" => "+55-910-491-1119",
                "gender" => "Genderqueer",
                "address" => "03148 Cascade Court",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/optioaspernaturmagni.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Pegeen",
                "last_name" => "MacGiolla",
                "username" => "pmacgiollao",
                "email" => "pmacgiollao@hp.com",
                "phone" => "+86-794-349-5326",
                "gender" => "Female",
                "address" => "6460 Donald Park",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Pegeen MacGiolla",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Loren",
                "last_name" => "Petschelt",
                "username" => "lpetscheltp",
                "email" => "lpetscheltp@epa.gov",
                "phone" => "+86-228-379-5711",
                "gender" => "Female",
                "address" => "948 Kinsman Circle",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Loren Petschelt",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Michaella",
                "last_name" => "Rennebach",
                "username" => "mrennebachq",
                "email" => "mrennebachq@webeden.co.uk",
                "phone" => "+385-489-351-0641",
                "gender" => "Female",
                "address" => "9 Maywood Center",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Michaella Rennebach",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Vinny",
                "last_name" => "Massy",
                "username" => "vmassyr",
                "email" => "vmassyr@springer.com",
                "phone" => "+46-994-137-4583",
                "gender" => "Male",
                "address" => "91074 Sunfield Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Vinny Massy",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Leonanie",
                "last_name" => "Aguilar",
                "username" => "laguilars",
                "email" => "laguilars@utexas.edu",
                "phone" => "+7-976-567-3124",
                "gender" => "Female",
                "address" => "1045 Sutherland Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Leonanie Aguilar",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Peirce",
                "last_name" => "Mabbott",
                "username" => "pmabbottt",
                "email" => "pmabbottt@fema.gov",
                "phone" => "+506-818-338-4885",
                "gender" => "Male",
                "address" => "0 Lawn Alley",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Peirce Mabbott",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Haley",
                "last_name" => "Gawke",
                "username" => "hgawkeu",
                "email" => "hgawkeu@spotify.com",
                "phone" => "+81-424-849-3444",
                "gender" => "Agender",
                "address" => "6373 Texas Crossing",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/deseruntquiased.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Deloria",
                "last_name" => "Skillern",
                "username" => "dskillernv",
                "email" => "dskillernv@google.cn",
                "phone" => "+86-819-576-8221",
                "gender" => "Female",
                "address" => "1 Messerschmidt Road",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Deloria Skillern",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Abrahan",
                "last_name" => "Lettley",
                "username" => "alettleyw",
                "email" => "alettleyw@go.com",
                "phone" => "+86-522-654-6052",
                "gender" => "Male",
                "address" => "785 Fieldstone Road",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Abrahan Lettley",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Aubrey",
                "last_name" => "Vasyatkin",
                "username" => "avasyatkinx",
                "email" => "avasyatkinx@chron.com",
                "phone" => "+51-932-300-0655",
                "gender" => "Polygender",
                "address" => "617 Kinsman Parkway",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/ipsadolorevel.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Aldridge",
                "last_name" => "Ballendine",
                "username" => "aballendiney",
                "email" => "aballendiney@deliciousdays.com",
                "phone" => "+225-727-915-8017",
                "gender" => "Male",
                "address" => "7352 Rockefeller Trail",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Aldridge Ballendine",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Aubert",
                "last_name" => "Brodie",
                "username" => "abrodiez",
                "email" => "abrodiez@reuters.com",
                "phone" => "+62-581-647-5294",
                "gender" => "Male",
                "address" => "14 Mockingbird Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Aubert Brodie",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Didi",
                "last_name" => "Mcmanaman",
                "username" => "dmcmanaman10",
                "email" => "dmcmanaman10@w3.org",
                "phone" => "+62-654-691-9570",
                "gender" => "Female",
                "address" => "039 Tomscot Point",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Didi Mcmanaman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Hunter",
                "last_name" => "Hardwicke",
                "username" => "hhardwicke11",
                "email" => "hhardwicke11@vk.com",
                "phone" => "+352-333-657-2993",
                "gender" => "Male",
                "address" => "4 Oriole Avenue",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Hunter Hardwicke",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Karlie",
                "last_name" => "Lagde",
                "username" => "klagde12",
                "email" => "klagde12@latimes.com",
                "phone" => "+48-751-436-7320",
                "gender" => "Female",
                "address" => "78 Moulton Avenue",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Karlie Lagde",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Gaultiero",
                "last_name" => "Drynan",
                "username" => "gdrynan13",
                "email" => "gdrynan13@bloglovin.com",
                "phone" => "+380-586-761-7114",
                "gender" => "Male",
                "address" => "051 Namekagon Center",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Gaultiero Drynan",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Jana",
                "last_name" => "Custy",
                "username" => "jcusty14",
                "email" => "jcusty14@webeden.co.uk",
                "phone" => "+33-873-728-1899",
                "gender" => "Female",
                "address" => "8916 Riverside Drive",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Jana Custy",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Madelina",
                "last_name" => "Jedrzej",
                "username" => "mjedrzej15",
                "email" => "mjedrzej15@bravesites.com",
                "phone" => "+52-178-349-0274",
                "gender" => "Female",
                "address" => "64 Northport Plaza",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Madelina Jedrzej",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Beverly",
                "last_name" => "Gerdes",
                "username" => "bgerdes16",
                "email" => "bgerdes16@de.vu",
                "phone" => "+62-372-133-7900",
                "gender" => "Female",
                "address" => "426 Maryland Crossing",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Beverly Gerdes",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Alie",
                "last_name" => "Rosendall",
                "username" => "arosendall17",
                "email" => "arosendall17@constantcontact.com",
                "phone" => "+55-316-172-8209",
                "gender" => "Female",
                "address" => "837 Red Cloud Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Alie Rosendall",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Melodie",
                "last_name" => "Lambell",
                "username" => "mlambell18",
                "email" => "mlambell18@imdb.com",
                "phone" => "+355-164-661-0025",
                "gender" => "Female",
                "address" => "61953 Bunker Hill Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Melodie Lambell",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Laurice",
                "last_name" => "Goulbourn",
                "username" => "lgoulbourn19",
                "email" => "lgoulbourn19@amazonaws.com",
                "phone" => "+81-500-366-1979",
                "gender" => "Female",
                "address" => "859 Debra Plaza",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Laurice Goulbourn",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Cornell",
                "last_name" => "Mallock",
                "username" => "cmallock1a",
                "email" => "cmallock1a@addtoany.com",
                "phone" => "+63-615-381-9376",
                "gender" => "Male",
                "address" => "7 Beilfuss Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Cornell Mallock",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Roxie",
                "last_name" => "Thew",
                "username" => "rthew1b",
                "email" => "rthew1b@narod.ru",
                "phone" => "+55-290-474-3466",
                "gender" => "Female",
                "address" => "23 Russell Lane",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Roxie Thew",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Willabella",
                "last_name" => "Lynagh",
                "username" => "wlynagh1c",
                "email" => "wlynagh1c@ustream.tv",
                "phone" => "+63-276-819-5867",
                "gender" => "Female",
                "address" => "51644 Banding Way",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Willabella Lynagh",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Brianne",
                "last_name" => "Gallichan",
                "username" => "bgallichan1d",
                "email" => "bgallichan1d@list-manage.com",
                "phone" => "+372-898-965-7697",
                "gender" => "Female",
                "address" => "4144 Northport Way",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Brianne Gallichan",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Sherlocke",
                "last_name" => "Kersting",
                "username" => "skersting1e",
                "email" => "skersting1e@webs.com",
                "phone" => "+7-181-975-4287",
                "gender" => "Male",
                "address" => "8 Summer Ridge Pass",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Sherlocke Kersting",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Daniela",
                "last_name" => "Atheis",
                "username" => "datheis1f",
                "email" => "datheis1f@state.tx.us",
                "phone" => "+86-761-366-0661",
                "gender" => "Female",
                "address" => "57 Farragut Point",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Daniela Atheis",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Kellby",
                "last_name" => "Leddy",
                "username" => "kleddy1g",
                "email" => "kleddy1g@livejournal.com",
                "phone" => "+62-166-175-7015",
                "gender" => "Male",
                "address" => "66417 Nova Hill",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Kellby Leddy",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Murvyn",
                "last_name" => "Battie",
                "username" => "mbattie1h",
                "email" => "mbattie1h@webnode.com",
                "phone" => "+60-341-741-4348",
                "gender" => "Male",
                "address" => "1 Truax Junction",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Murvyn Battie",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Laurette",
                "last_name" => "Perrigo",
                "username" => "lperrigo1i",
                "email" => "lperrigo1i@nba.com",
                "phone" => "+95-840-657-9093",
                "gender" => "Female",
                "address" => "16875 Sunbrook Junction",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Laurette Perrigo",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Sidoney",
                "last_name" => "MacNamara",
                "username" => "smacnamara1j",
                "email" => "smacnamara1j@marketwatch.com",
                "phone" => "+86-386-764-0955",
                "gender" => "Female",
                "address" => "13 Chinook Court",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Sidoney MacNamara",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Bradan",
                "last_name" => "Furman",
                "username" => "bfurman1k",
                "email" => "bfurman1k@google.it",
                "phone" => "+62-638-843-0915",
                "gender" => "Male",
                "address" => "0 Cardinal Pass",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Bradan Furman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Vivianna",
                "last_name" => "Goadby",
                "username" => "vgoadby1l",
                "email" => "vgoadby1l@apple.com",
                "phone" => "+86-735-407-2208",
                "gender" => "Female",
                "address" => "14 Forest Junction",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Vivianna Goadby",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Kermy",
                "last_name" => "Orcott",
                "username" => "korcott1m",
                "email" => "korcott1m@alexa.com",
                "phone" => "+46-125-377-4851",
                "gender" => "Male",
                "address" => "7004 Main Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Kermy Orcott",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Vassily",
                "last_name" => "MacAindreis",
                "username" => "vmacaindreis1n",
                "email" => "vmacaindreis1n@deliciousdays.com",
                "phone" => "+62-856-653-4257",
                "gender" => "Male",
                "address" => "2245 Cardinal Trail",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Vassily MacAindreis",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Felicity",
                "last_name" => "Pittham",
                "username" => "fpittham1o",
                "email" => "fpittham1o@cafepress.com",
                "phone" => "+55-380-722-8412",
                "gender" => "Female",
                "address" => "56858 Fulton Park",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Felicity Pittham",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Rori",
                "last_name" => "Tomala",
                "username" => "rtomala1p",
                "email" => "rtomala1p@psu.edu",
                "phone" => "+86-359-587-8879",
                "gender" => "Genderqueer",
                "address" => "0 Ronald Regan Alley",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/cumquequaeratfugit.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Stacy",
                "last_name" => "Marven",
                "username" => "smarven1q",
                "email" => "smarven1q@sciencedaily.com",
                "phone" => "+86-224-818-4662",
                "gender" => "Male",
                "address" => "52099 Green Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Stacy Marven",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Valerie",
                "last_name" => "Ickowicz",
                "username" => "vickowicz1r",
                "email" => "vickowicz1r@usnews.com",
                "phone" => "+62-132-642-2293",
                "gender" => "Female",
                "address" => "7132 Cody Lane",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Valerie Ickowicz",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Shirlee",
                "last_name" => "Sandyfirth",
                "username" => "ssandyfirth1s",
                "email" => "ssandyfirth1s@comsenz.com",
                "phone" => "+55-225-262-9806",
                "gender" => "Female",
                "address" => "7214 Cascade Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Shirlee Sandyfirth",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Virgil",
                "last_name" => "Peerman",
                "username" => "vpeerman1t",
                "email" => "vpeerman1t@arizona.edu",
                "phone" => "+420-715-764-6365",
                "gender" => "Male",
                "address" => "16568 Johnson Pass",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Virgil Peerman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Grant",
                "last_name" => "Bere",
                "username" => "gbere1u",
                "email" => "gbere1u@flavors.me",
                "phone" => "+86-700-980-4086",
                "gender" => "Male",
                "address" => "194 Hoard Alley",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Grant Bere",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Hashim",
                "last_name" => "O'Haire",
                "username" => "hohaire1v",
                "email" => "hohaire1v@ustream.tv",
                "phone" => "+86-155-745-3734",
                "gender" => "Male",
                "address" => "2 Pine View Avenue",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Hashim Haire",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Rose",
                "last_name" => "Cromer",
                "username" => "rcromer1w",
                "email" => "rcromer1w@cnn.com",
                "phone" => "+963-568-596-2418",
                "gender" => "Female",
                "address" => "8049 Golf Course Court",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Rose Cromer",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Micheline",
                "last_name" => "Adnett",
                "username" => "madnett1x",
                "email" => "madnett1x@smh.com.au",
                "phone" => "+86-782-797-6414",
                "gender" => "Female",
                "address" => "737 Melvin Way",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Micheline Adnett",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Theda",
                "last_name" => "Knudsen",
                "username" => "tknudsen1y",
                "email" => "tknudsen1y@kickstarter.com",
                "phone" => "+60-952-816-2260",
                "gender" => "Female",
                "address" => "4 Shoshone Court",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Theda Knudsen",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Neddy",
                "last_name" => "De Dei",
                "username" => "ndedei1z",
                "email" => "ndedei1z@istockphoto.com",
                "phone" => "+234-700-114-2853",
                "gender" => "Male",
                "address" => "89414 Charing Cross Point",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Neddy Dei",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Ikey",
                "last_name" => "Bruun",
                "username" => "ibruun20",
                "email" => "ibruun20@icio.us",
                "phone" => "+380-221-935-4059",
                "gender" => "Male",
                "address" => "922 Hauk Avenue",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Ikey Bruun",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Jarad",
                "last_name" => "Sinnock",
                "username" => "jsinnock21",
                "email" => "jsinnock21@wikipedia.org",
                "phone" => "+86-757-391-6870",
                "gender" => "Male",
                "address" => "9617 Declaration Hill",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Jarad Sinnock",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Carlyn",
                "last_name" => "Ciobotaro",
                "username" => "cciobotaro22",
                "email" => "cciobotaro22@hexun.com",
                "phone" => "+351-271-858-0552",
                "gender" => "Female",
                "address" => "23575 Vahlen Circle",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Carlyn Ciobotaro",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Tilda",
                "last_name" => "Walworth",
                "username" => "twalworth23",
                "email" => "twalworth23@blogger.com",
                "phone" => "+66-838-567-5246",
                "gender" => "Genderqueer",
                "address" => "3 Garrison Trail",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/utcorporishic.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Idalina",
                "last_name" => "Letham",
                "username" => "iletham24",
                "email" => "iletham24@youku.com",
                "phone" => "+66-416-148-4332",
                "gender" => "Female",
                "address" => "35 Homewood Court",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Idalina Letham",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Tynan",
                "last_name" => "Bream",
                "username" => "tbream25",
                "email" => "tbream25@baidu.com",
                "phone" => "+86-427-922-6348",
                "gender" => "Male",
                "address" => "2399 Carioca Avenue",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Tynan Bream",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Danika",
                "last_name" => "Abrahamsson",
                "username" => "dabrahamsson26",
                "email" => "dabrahamsson26@guardian.co.uk",
                "phone" => "+1-449-610-2205",
                "gender" => "Female",
                "address" => "451 Springview Plaza",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Danika Abrahamsson",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Tracy",
                "last_name" => "Trodden",
                "username" => "ttrodden27",
                "email" => "ttrodden27@ifeng.com",
                "phone" => "+1-734-165-9097",
                "gender" => "Female",
                "address" => "7 Dexter Junction",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Tracy Trodden",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Sidney",
                "last_name" => "Eloi",
                "username" => "seloi28",
                "email" => "seloi28@vkontakte.ru",
                "phone" => "+86-620-379-5209",
                "gender" => "Male",
                "address" => "92 Cardinal Drive",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Sidney Eloi",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Joaquin",
                "last_name" => "Cicchetto",
                "username" => "jcicchetto29",
                "email" => "jcicchetto29@networksolutions.com",
                "phone" => "+86-883-696-6364",
                "gender" => "Male",
                "address" => "11439 Forster Hill",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Joaquin Cicchetto",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Gustie",
                "last_name" => "Slopier",
                "username" => "gslopier2a",
                "email" => "gslopier2a@weather.com",
                "phone" => "+61-515-850-0280",
                "gender" => "Female",
                "address" => "91 Hovde Avenue",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Gustie Slopier",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Riannon",
                "last_name" => "Seath",
                "username" => "rseath2b",
                "email" => "rseath2b@census.gov",
                "phone" => "+7-104-189-5036",
                "gender" => "Female",
                "address" => "3924 Elmside Park",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Riannon Seath",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Cecil",
                "last_name" => "Schruurs",
                "username" => "cschruurs2c",
                "email" => "cschruurs2c@auda.org.au",
                "phone" => "+62-815-156-2340",
                "gender" => "Male",
                "address" => "121 Milwaukee Way",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Cecil Schruurs",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Cortie",
                "last_name" => "Heathcott",
                "username" => "cheathcott2d",
                "email" => "cheathcott2d@cbc.ca",
                "phone" => "+351-517-642-3272",
                "gender" => "Male",
                "address" => "5382 Evergreen Way",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Cortie Heathcott",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Neill",
                "last_name" => "Barus",
                "username" => "nbarus2e",
                "email" => "nbarus2e@nhs.uk",
                "phone" => "+64-974-565-4829",
                "gender" => "Male",
                "address" => "749 Myrtle Hill",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Neill Barus",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Sarene",
                "last_name" => "Slimings",
                "username" => "sslimings2f",
                "email" => "sslimings2f@timesonline.co.uk",
                "phone" => "+86-666-963-3327",
                "gender" => "Female",
                "address" => "495 Village Circle",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Sarene Slimings",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Jarib",
                "last_name" => "Tanner",
                "username" => "jtanner2g",
                "email" => "jtanner2g@businessweek.com",
                "phone" => "+7-917-738-5665",
                "gender" => "Non-binary",
                "address" => "9106 Harper Road",
                "age" => rand(15,30),
                "avatar" => "https://robohash.org/facereeaexcepturi.png?size=50x50&set=set1",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Royall",
                "last_name" => "Beadman",
                "username" => "rbeadman2h",
                "email" => "rbeadman2h@symantec.com",
                "phone" => "+62-390-276-2861",
                "gender" => "Male",
                "address" => "41567 Kipling Pass",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Royall Beadman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Em",
                "last_name" => "Poate",
                "username" => "epoate2i",
                "email" => "epoate2i@springer.com",
                "phone" => "+66-397-705-1125",
                "gender" => "Male",
                "address" => "5269 Fisk Plaza",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Em Poate",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Seumas",
                "last_name" => "Byrnes",
                "username" => "sbyrnes2j",
                "email" => "sbyrnes2j@ox.ac.uk",
                "phone" => "+57-252-896-0812",
                "gender" => "Male",
                "address" => "0687 Becker Pass",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Seumas Byrnes",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Dionisio",
                "last_name" => "Morrott",
                "username" => "dmorrott2k",
                "email" => "dmorrott2k@economist.com",
                "phone" => "+255-584-638-5956",
                "gender" => "Male",
                "address" => "70632 Grayhawk Street",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Dionisio Morrott",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Hagen",
                "last_name" => "Edinburough",
                "username" => "hedinburough2l",
                "email" => "hedinburough2l@hubpages.com",
                "phone" => "+33-672-462-1915",
                "gender" => "Male",
                "address" => "9466 West Parkway",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Hagen Edinburough",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Jandy",
                "last_name" => "Kitman",
                "username" => "jkitman2m",
                "email" => "jkitman2m@nydailynews.com",
                "phone" => "+351-978-818-1160",
                "gender" => "Female",
                "address" => "850 Quincy Drive",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Jandy Kitman",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Granger",
                "last_name" => "Pedler",
                "username" => "gpedler2n",
                "email" => "gpedler2n@shop-pro.jp",
                "phone" => "+86-668-724-9016",
                "gender" => "Male",
                "address" => "84321 Pierstorff Lane",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Granger Pedler",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Vasilis",
                "last_name" => "Toll",
                "username" => "vtoll2o",
                "email" => "vtoll2o@who.int",
                "phone" => "+7-923-451-5529",
                "gender" => "Male",
                "address" => "0190 Cordelia Terrace",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Vasilis Toll",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Abel",
                "last_name" => "Costley",
                "username" => "acostley2p",
                "email" => "acostley2p@google.co.jp",
                "phone" => "+47-934-769-6785",
                "gender" => "Male",
                "address" => "6 Stone Corner Plaza",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?top%5B%5D=dreads01,dreads02,eyepatch,frizzle,shortCurly,shortFlat,shortRound,shortWaved,sides,theCaesar,theCaesarAndSidePart,turban&seed=Abel Costley",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Marianna",
                "last_name" => "Gymblett",
                "username" => "mgymblett2q",
                "email" => "mgymblett2q@dagondesign.com",
                "phone" => "+44-400-972-9981",
                "gender" => "Female",
                "address" => "365 Weeping Birch Trail",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Marianna Gymblett",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ],
            [
                "first_name" => "Krissie",
                "last_name" => "Page",
                "username" => "kpage2r",
                "email" => "kpage2r@eepurl.com",
                "phone" => "+86-293-102-6435",
                "gender" => "Female",
                "address" => "67688 Victoria Alley",
                "age" => rand(15,30),
                "avatar" => "https://api.dicebear.com/5.x/avataaars/svg?facialHairProbability=0&top%5B%5D=bigHair,bob,bun,curly,curvy,dreads,frida,fro,hijab,longButNotTooLong,miaWallace,shaggy,shaggyMullet,shavedSides,straightAndStrand,straight01,straight02&seed=Krissie Page",
                "created_id" => 1,
                "created_at" => Carbon::now()
            ]
        ]);
    }
}
