<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class m_colors_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table(env('TABLE_PREFIX').'m_colors')->insert([
            [ 'group' => 'background', 'code' => 'bg-base-100', 'hex' => '#fff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-base-200', 'hex' => '#f9fafb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-base-300', 'hex' => '#d1d5db', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-base-content', 'hex' => '#1f2937', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-black', 'hex' => '#000', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-white', 'hex' => '#fff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-50', 'hex' => '#f8fafc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-100', 'hex' => '#f1f5f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-200', 'hex' => '#e2e8f0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-300', 'hex' => '#cbd5e1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-400', 'hex' => '#94a3b8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-500', 'hex' => '#64748b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-600', 'hex' => '#475569', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-700', 'hex' => '#334155', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-800', 'hex' => '#1e293b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-slate-900', 'hex' => '#0f172a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-50', 'hex' => '#f9fafb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-100', 'hex' => '#f3f4f6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-200', 'hex' => '#e5e7eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-300', 'hex' => '#d1d5db', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-400', 'hex' => '#9ca3af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-500', 'hex' => '#6b7280', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-600', 'hex' => '#4b5563', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-700', 'hex' => '#374151', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-800', 'hex' => '#1f2937', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-gray-900', 'hex' => '#111827', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-50', 'hex' => '#fafafa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-100', 'hex' => '#f4f4f5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-200', 'hex' => '#e4e4e7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-300', 'hex' => '#d4d4d8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-400', 'hex' => '#a1a1aa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-500', 'hex' => '#71717a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-600', 'hex' => '#52525b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-700', 'hex' => '#3f3f46', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-800', 'hex' => '#27272a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-zinc-900', 'hex' => '#18181b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-50', 'hex' => '#fafaf9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-100', 'hex' => '#f5f5f4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-200', 'hex' => '#e7e5e4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-300', 'hex' => '#d6d3d1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-400', 'hex' => '#a8a29e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-500', 'hex' => '#78716c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-600', 'hex' => '#57534e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-700', 'hex' => '#44403c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-800', 'hex' => '#292524', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-stone-900', 'hex' => '#1c1917', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-50', 'hex' => '#fef2f2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-100', 'hex' => '#fee2e2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-200', 'hex' => '#fecaca', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-300', 'hex' => '#fca5a5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-400', 'hex' => '#f87171', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-500', 'hex' => '#ef4444', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-600', 'hex' => '#dc2626', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-700', 'hex' => '#b91c1c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-800', 'hex' => '#991b1b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-red-900', 'hex' => '#7f1d1d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-50', 'hex' => '#fff7ed', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-100', 'hex' => '#ffedd5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-200', 'hex' => '#fed7aa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-300', 'hex' => '#fdba74', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-400', 'hex' => '#fb923c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-500', 'hex' => '#f97316', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-600', 'hex' => '#ea580c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-700', 'hex' => '#c2410c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-800', 'hex' => '#9a3412', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-orange-900', 'hex' => '#7c2d12', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-50', 'hex' => '#fffbeb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-100', 'hex' => '#fef3c7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-200', 'hex' => '#fde68a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-300', 'hex' => '#fcd34d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-400', 'hex' => '#fbbf24', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-500', 'hex' => '#f59e0b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-600', 'hex' => '#d97706', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-700', 'hex' => '#b45309', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-800', 'hex' => '#92400e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-amber-900', 'hex' => '#78350f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-50', 'hex' => '#fefce8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-100', 'hex' => '#fef9c3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-200', 'hex' => '#fef08a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-300', 'hex' => '#fde047', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-400', 'hex' => '#facc15', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-500', 'hex' => '#eab308', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-600', 'hex' => '#ca8a04', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-700', 'hex' => '#a16207', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-800', 'hex' => '#854d0e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-yellow-900', 'hex' => '#713f12', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-50', 'hex' => '#f7fee7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-100', 'hex' => '#ecfccb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-200', 'hex' => '#d9f99d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-300', 'hex' => '#bef264', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-400', 'hex' => '#a3e635', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-500', 'hex' => '#84cc16', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-600', 'hex' => '#65a30d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-700', 'hex' => '#4d7c0f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-800', 'hex' => '#3f6212', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-lime-900', 'hex' => '#365314', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-50', 'hex' => '#f0fdf4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-100', 'hex' => '#dcfce7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-200', 'hex' => '#bbf7d0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-300', 'hex' => '#86efac', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-400', 'hex' => '#4ade80', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-500', 'hex' => '#22c55e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-600', 'hex' => '#16a34a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-700', 'hex' => '#15803d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-800', 'hex' => '#166534', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-green-900', 'hex' => '#14532d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-50', 'hex' => '#ecfdf5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-100', 'hex' => '#d1fae5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-200', 'hex' => '#a7f3d0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-300', 'hex' => '#6ee7b7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-400', 'hex' => '#34d399', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-500', 'hex' => '#10b981', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-600', 'hex' => '#059669', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-700', 'hex' => '#047857', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-800', 'hex' => '#065f46', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-emerald-900', 'hex' => '#064e3b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-50', 'hex' => '#f0fdfa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-100', 'hex' => '#ccfbf1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-200', 'hex' => '#99f6e4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-300', 'hex' => '#5eead4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-400', 'hex' => '#2dd4bf', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-500', 'hex' => '#14b8a6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-600', 'hex' => '#0d9488', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-700', 'hex' => '#0f766e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-800', 'hex' => '#115e59', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-teal-900', 'hex' => '#134e4a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-50', 'hex' => '#ecfeff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-100', 'hex' => '#cffafe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-200', 'hex' => '#a5f3fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-300', 'hex' => '#67e8f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-400', 'hex' => '#22d3ee', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-500', 'hex' => '#06b6d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-600', 'hex' => '#0891b2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-700', 'hex' => '#0e7490', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-800', 'hex' => '#155e75', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-cyan-900', 'hex' => '#164e63', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-50', 'hex' => '#f0f9ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-100', 'hex' => '#e0f2fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-200', 'hex' => '#bae6fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-300', 'hex' => '#7dd3fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-400', 'hex' => '#38bdf8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-500', 'hex' => '#0ea5e9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-600', 'hex' => '#0284c7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-700', 'hex' => '#0369a1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-800', 'hex' => '#075985', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-sky-900', 'hex' => '#0c4a6e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-50', 'hex' => '#eff6ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-100', 'hex' => '#dbeafe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-200', 'hex' => '#bfdbfe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-300', 'hex' => '#93c5fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-400', 'hex' => '#60a5fa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-500', 'hex' => '#3b82f6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-600', 'hex' => '#2563eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-700', 'hex' => '#1d4ed8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-800', 'hex' => '#1e40af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-blue-900', 'hex' => '#1e3a8a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-50', 'hex' => '#eef2ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-100', 'hex' => '#e0e7ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-200', 'hex' => '#c7d2fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-300', 'hex' => '#a5b4fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-400', 'hex' => '#818cf8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-500', 'hex' => '#6366f1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-600', 'hex' => '#4f46e5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-700', 'hex' => '#4338ca', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-800', 'hex' => '#3730a3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-indigo-900', 'hex' => '#312e81', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-50', 'hex' => '#f5f3ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-100', 'hex' => '#ede9fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-200', 'hex' => '#ddd6fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-300', 'hex' => '#c4b5fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-400', 'hex' => '#a78bfa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-500', 'hex' => '#8b5cf6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-600', 'hex' => '#7c3aed', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-700', 'hex' => '#6d28d9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-800', 'hex' => '#5b21b6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-violet-900', 'hex' => '#4c1d95', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-50', 'hex' => '#faf5ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-100', 'hex' => '#f3e8ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-200', 'hex' => '#e9d5ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-300', 'hex' => '#d8b4fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-400', 'hex' => '#c084fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-500', 'hex' => '#a855f7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-600', 'hex' => '#9333ea', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-700', 'hex' => '#7e22ce', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-800', 'hex' => '#6b21a8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-purple-900', 'hex' => '#581c87', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-50', 'hex' => '#fdf4ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-100', 'hex' => '#fae8ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-200', 'hex' => '#f5d0fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-300', 'hex' => '#f0abfc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-400', 'hex' => '#e879f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-500', 'hex' => '#d946ef', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-600', 'hex' => '#c026d3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-700', 'hex' => '#a21caf', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-800', 'hex' => '#86198f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-fuchsia-900', 'hex' => '#701a75', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-50', 'hex' => '#fdf2f8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-100', 'hex' => '#fce7f3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-200', 'hex' => '#fbcfe8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-300', 'hex' => '#f9a8d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-400', 'hex' => '#f472b6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-500', 'hex' => '#ec4899', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-600', 'hex' => '#db2777', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-700', 'hex' => '#be185d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-800', 'hex' => '#9d174d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-pink-900', 'hex' => '#831843', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-50', 'hex' => '#fff1f2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-100', 'hex' => '#ffe4e6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-200', 'hex' => '#fecdd3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-300', 'hex' => '#fda4af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-400', 'hex' => '#fb7185', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-500', 'hex' => '#f43f5e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-600', 'hex' => '#e11d48', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-700', 'hex' => '#be123c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-800', 'hex' => '#9f1239', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-rose-900', 'hex' => '#881337', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-50', 'hex' => '#fafafa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-100', 'hex' => '#f5f5f5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-200', 'hex' => '#e5e5e5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-300', 'hex' => '#d4d4d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-400', 'hex' => '#a3a3a3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-500', 'hex' => '#737373', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-600', 'hex' => '#525252', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-700', 'hex' => '#404040', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-800', 'hex' => '#262626', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'background', 'code' => 'bg-true-gray-900', 'hex' => '#171717', 'created_id' => 1, 'created_at' => Carbon::now() ],



            [ 'group' => 'text', 'code' => 'text-base-100', 'hex' => '#fff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-base-200', 'hex' => '#f9fafb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-base-300', 'hex' => '#d1d5db', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-base-content', 'hex' => '#1f2937', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-black', 'hex' => '#000', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-white','hex' => '#fff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-50','hex' => '#f8fafc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-100','hex' => '#f1f5f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-200','hex' => '#e2e8f0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-300','hex' => '#cbd5e1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-400','hex' => '#94a3b8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-500','hex' => '#64748b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-600','hex' => '#475569', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-700','hex' => '#334155', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-800','hex' => '#1e293b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-slate-900','hex' => '#0f172a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-50','hex' => '#f9fafb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-100','hex' => '#f3f4f6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-200','hex' => '#e5e7eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-300','hex' => '#d1d5db', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-400','hex' => '#9ca3af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-500','hex' => '#6b7280', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-600','hex' => '#4b5563', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-700','hex' => '#374151', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-800','hex' => '#1f2937', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-gray-900','hex' => '#111827', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-50','hex' => '#fafafa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-100','hex' => '#f4f4f5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-200','hex' => '#e4e4e7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-300','hex' => '#d4d4d8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-400','hex' => '#a1a1aa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-500','hex' => '#71717a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-600','hex' => '#52525b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-700','hex' => '#3f3f46', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-800','hex' => '#27272a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-zinc-900','hex' => '#18181b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-50','hex' => '#fafaf9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-100','hex' => '#f5f5f4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-200','hex' => '#e7e5e4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-300','hex' => '#d6d3d1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-400','hex' => '#a8a29e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-500','hex' => '#78716c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-600','hex' => '#57534e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-700','hex' => '#44403c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-800','hex' => '#292524', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-stone-900','hex' => '#1c1917', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-50','hex' => '#fef2f2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-100','hex' => '#fee2e2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-200','hex' => '#fecaca', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-300','hex' => '#fca5a5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-400','hex' => '#f87171', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-500','hex' => '#ef4444', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-600','hex' => '#dc2626', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-700','hex' => '#b91c1c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-800','hex' => '#991b1b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-red-900','hex' => '#7f1d1d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-50','hex' => '#fff7ed', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-100','hex' => '#ffedd5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-200','hex' => '#fed7aa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-300','hex' => '#fdba74', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-400','hex' => '#fb923c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-500','hex' => '#f97316', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-600','hex' => '#ea580c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-700','hex' => '#c2410c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-800','hex' => '#9a3412', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-orange-900','hex' => '#7c2d12', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-50','hex' => '#fffbeb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-100','hex' => '#fef3c7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-200','hex' => '#fde68a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-300','hex' => '#fcd34d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-400','hex' => '#fbbf24', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-500','hex' => '#f59e0b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-600','hex' => '#d97706', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-700','hex' => '#b45309', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-800','hex' => '#92400e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-amber-900','hex' => '#78350f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-50','hex' => '#fefce8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-100','hex' => '#fef9c3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-200','hex' => '#fef08a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-300','hex' => '#fde047', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-400','hex' => '#facc15', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-500','hex' => '#eab308', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-600','hex' => '#ca8a04', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-700','hex' => '#a16207', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-800','hex' => '#854d0e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-yellow-900','hex' => '#713f12', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-50','hex' => '#f7fee7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-100','hex' => '#ecfccb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-200','hex' => '#d9f99d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-300','hex' => '#bef264', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-400','hex' => '#a3e635', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-500','hex' => '#84cc16', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-600','hex' => '#65a30d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-700','hex' => '#4d7c0f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-800','hex' => '#3f6212', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-lime-900','hex' => '#365314', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-50','hex' => '#f0fdf4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-100','hex' => '#dcfce7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-200','hex' => '#bbf7d0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-300','hex' => '#86efac', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-400','hex' => '#4ade80', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-500','hex' => '#22c55e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-600','hex' => '#16a34a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-700','hex' => '#15803d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-800','hex' => '#166534', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-green-900','hex' => '#14532d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-50','hex' => '#ecfdf5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-100','hex' => '#d1fae5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-200','hex' => '#a7f3d0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-300','hex' => '#6ee7b7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-400','hex' => '#34d399', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-500','hex' => '#10b981', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-600','hex' => '#059669', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-700','hex' => '#047857', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-800','hex' => '#065f46', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-emerald-900','hex' => '#064e3b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-50','hex' => '#f0fdfa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-100','hex' => '#ccfbf1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-200','hex' => '#99f6e4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-300','hex' => '#5eead4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-400','hex' => '#2dd4bf', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-500','hex' => '#14b8a6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-600','hex' => '#0d9488', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-700','hex' => '#0f766e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-800','hex' => '#115e59', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-teal-900','hex' => '#134e4a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-50','hex' => '#ecfeff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-100','hex' => '#cffafe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-200','hex' => '#a5f3fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-300','hex' => '#67e8f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-400','hex' => '#22d3ee', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-500','hex' => '#06b6d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-600','hex' => '#0891b2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-700','hex' => '#0e7490', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-800','hex' => '#155e75', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-cyan-900','hex' => '#164e63', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-50','hex' => '#f0f9ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-100','hex' => '#e0f2fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-200','hex' => '#bae6fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-300','hex' => '#7dd3fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-400','hex' => '#38bdf8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-500','hex' => '#0ea5e9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-600','hex' => '#0284c7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-700','hex' => '#0369a1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-800','hex' => '#075985', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-sky-900','hex' => '#0c4a6e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-50','hex' => '#eff6ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-100','hex' => '#dbeafe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-200','hex' => '#bfdbfe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-300','hex' => '#93c5fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-400','hex' => '#60a5fa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-500','hex' => '#3b82f6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-600','hex' => '#2563eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-700','hex' => '#1d4ed8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-800','hex' => '#1e40af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-blue-900','hex' => '#1e3a8a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-50','hex' => '#eef2ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-100','hex' => '#e0e7ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-200','hex' => '#c7d2fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-300','hex' => '#a5b4fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-400','hex' => '#818cf8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-500','hex' => '#6366f1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-600','hex' => '#4f46e5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-700','hex' => '#4338ca', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-800','hex' => '#3730a3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-indigo-900','hex' => '#312e81', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-50','hex' => '#f5f3ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-100','hex' => '#ede9fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-200','hex' => '#ddd6fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-300','hex' => '#c4b5fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-400','hex' => '#a78bfa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-500','hex' => '#8b5cf6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-600','hex' => '#7c3aed', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-700','hex' => '#6d28d9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-800','hex' => '#5b21b6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-violet-900','hex' => '#4c1d95', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-50','hex' => '#faf5ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-100','hex' => '#f3e8ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-200','hex' => '#e9d5ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-300','hex' => '#d8b4fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-400','hex' => '#c084fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-500','hex' => '#a855f7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-600','hex' => '#9333ea', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-700','hex' => '#7e22ce', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-800','hex' => '#6b21a8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-purple-900','hex' => '#581c87', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-50','hex' => '#fdf4ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-100','hex' => '#fae8ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-200','hex' => '#f5d0fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-300','hex' => '#f0abfc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-400','hex' => '#e879f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-500','hex' => '#d946ef', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-600','hex' => '#c026d3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-700','hex' => '#a21caf', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-800','hex' => '#86198f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-fuchsia-900','hex' => '#701a75', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-50','hex' => '#fdf2f8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-100','hex' => '#fce7f3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-200','hex' => '#fbcfe8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-300','hex' => '#f9a8d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-400','hex' => '#f472b6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-500','hex' => '#ec4899', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-600','hex' => '#db2777', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-700','hex' => '#be185d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-800','hex' => '#9d174d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-pink-900','hex' => '#831843', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-50','hex' => '#fff1f2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-100','hex' => '#ffe4e6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-200','hex' => '#fecdd3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-300','hex' => '#fda4af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-400','hex' => '#fb7185', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-500','hex' => '#f43f5e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-600','hex' => '#e11d48', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-700','hex' => '#be123c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-800','hex' => '#9f1239', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-rose-900','hex' => '#881337', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-50','hex' => '#fafafa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-100','hex' => '#f5f5f5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-200','hex' => '#e5e5e5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-300','hex' => '#d4d4d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-400','hex' => '#a3a3a3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-500','hex' => '#737373', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-600','hex' => '#525252', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-700','hex' => '#404040', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-800','hex' => '#262626', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'text', 'code' => 'text-true-gray-900','hex' => '#171717', 'created_id' => 1, 'created_at' => Carbon::now() ],



            [ 'group' => 'border', 'code' => 'border-base-100', 'hex' => '#fff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-base-200', 'hex' => '#f9fafb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-base-300', 'hex' => '#d1d5db', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-base-content', 'hex' => '#1f2937', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-black', 'hex' => '#000', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-white', 'hex' => '#fff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-50', 'hex' => '#f8fafc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-100', 'hex' => '#f1f5f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-200', 'hex' => '#e2e8f0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-300', 'hex' => '#cbd5e1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-400', 'hex' => '#94a3b8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-500', 'hex' => '#64748b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-600', 'hex' => '#475569', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-700', 'hex' => '#334155', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-800', 'hex' => '#1e293b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-slate-900', 'hex' => '#0f172a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-50', 'hex' => '#f9fafb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-100', 'hex' => '#f3f4f6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-200', 'hex' => '#e5e7eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-300', 'hex' => '#d1d5db', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-400', 'hex' => '#9ca3af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-500', 'hex' => '#6b7280', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-600', 'hex' => '#4b5563', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-700', 'hex' => '#374151', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-800', 'hex' => '#1f2937', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-gray-900', 'hex' => '#111827', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-50', 'hex' => '#fafafa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-100', 'hex' => '#f4f4f5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-200', 'hex' => '#e4e4e7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-300', 'hex' => '#d4d4d8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-400', 'hex' => '#a1a1aa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-500', 'hex' => '#71717a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-600', 'hex' => '#52525b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-700', 'hex' => '#3f3f46', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-800', 'hex' => '#27272a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-zinc-900', 'hex' => '#18181b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-50', 'hex' => '#fafaf9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-100', 'hex' => '#f5f5f4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-200', 'hex' => '#e7e5e4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-300', 'hex' => '#d6d3d1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-400', 'hex' => '#a8a29e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-500', 'hex' => '#78716c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-600', 'hex' => '#57534e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-700', 'hex' => '#44403c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-800', 'hex' => '#292524', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-stone-900', 'hex' => '#1c1917', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-50', 'hex' => '#fef2f2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-100', 'hex' => '#fee2e2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-200', 'hex' => '#fecaca', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-300', 'hex' => '#fca5a5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-400', 'hex' => '#f87171', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-500', 'hex' => '#ef4444', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-600', 'hex' => '#dc2626', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-700', 'hex' => '#b91c1c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-800', 'hex' => '#991b1b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-red-900', 'hex' => '#7f1d1d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-50', 'hex' => '#fff7ed', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-100', 'hex' => '#ffedd5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-200', 'hex' => '#fed7aa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-300', 'hex' => '#fdba74', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-400', 'hex' => '#fb923c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-500', 'hex' => '#f97316', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-600', 'hex' => '#ea580c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-700', 'hex' => '#c2410c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-800', 'hex' => '#9a3412', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-orange-900', 'hex' => '#7c2d12', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-50', 'hex' => '#fffbeb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-100', 'hex' => '#fef3c7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-200', 'hex' => '#fde68a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-300', 'hex' => '#fcd34d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-400', 'hex' => '#fbbf24', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-500', 'hex' => '#f59e0b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-600', 'hex' => '#d97706', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-700', 'hex' => '#b45309', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-800', 'hex' => '#92400e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-amber-900', 'hex' => '#78350f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-50', 'hex' => '#fefce8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-100', 'hex' => '#fef9c3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-200', 'hex' => '#fef08a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-300', 'hex' => '#fde047', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-400', 'hex' => '#facc15', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-500', 'hex' => '#eab308', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-600', 'hex' => '#ca8a04', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-700', 'hex' => '#a16207', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-800', 'hex' => '#854d0e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-yellow-900', 'hex' => '#713f12', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-50', 'hex' => '#f7fee7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-100', 'hex' => '#ecfccb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-200', 'hex' => '#d9f99d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-300', 'hex' => '#bef264', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-400', 'hex' => '#a3e635', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-500', 'hex' => '#84cc16', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-600', 'hex' => '#65a30d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-700', 'hex' => '#4d7c0f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-800', 'hex' => '#3f6212', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-lime-900', 'hex' => '#365314', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-50', 'hex' => '#f0fdf4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-100', 'hex' => '#dcfce7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-200', 'hex' => '#bbf7d0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-300', 'hex' => '#86efac', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-400', 'hex' => '#4ade80', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-500', 'hex' => '#22c55e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-600', 'hex' => '#16a34a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-700', 'hex' => '#15803d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-800', 'hex' => '#166534', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-green-900', 'hex' => '#14532d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-50', 'hex' => '#ecfdf5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-100', 'hex' => '#d1fae5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-200', 'hex' => '#a7f3d0', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-300', 'hex' => '#6ee7b7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-400', 'hex' => '#34d399', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-500', 'hex' => '#10b981', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-600', 'hex' => '#059669', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-700', 'hex' => '#047857', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-800', 'hex' => '#065f46', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-emerald-900', 'hex' => '#064e3b', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-50', 'hex' => '#f0fdfa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-100', 'hex' => '#ccfbf1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-200', 'hex' => '#99f6e4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-300', 'hex' => '#5eead4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-400', 'hex' => '#2dd4bf', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-500', 'hex' => '#14b8a6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-600', 'hex' => '#0d9488', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-700', 'hex' => '#0f766e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-800', 'hex' => '#115e59', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-teal-900', 'hex' => '#134e4a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-50', 'hex' => '#ecfeff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-100', 'hex' => '#cffafe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-200', 'hex' => '#a5f3fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-300', 'hex' => '#67e8f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-400', 'hex' => '#22d3ee', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-500', 'hex' => '#06b6d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-600', 'hex' => '#0891b2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-700', 'hex' => '#0e7490', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-800', 'hex' => '#155e75', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-cyan-900', 'hex' => '#164e63', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-50', 'hex' => '#f0f9ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-100', 'hex' => '#e0f2fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-200', 'hex' => '#bae6fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-300', 'hex' => '#7dd3fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-400', 'hex' => '#38bdf8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-500', 'hex' => '#0ea5e9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-600', 'hex' => '#0284c7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-700', 'hex' => '#0369a1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-800', 'hex' => '#075985', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-sky-900', 'hex' => '#0c4a6e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-50', 'hex' => '#eff6ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-100', 'hex' => '#dbeafe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-200', 'hex' => '#bfdbfe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-300', 'hex' => '#93c5fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-400', 'hex' => '#60a5fa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-500', 'hex' => '#3b82f6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-600', 'hex' => '#2563eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-700', 'hex' => '#1d4ed8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-800', 'hex' => '#1e40af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-blue-900', 'hex' => '#1e3a8a', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-50', 'hex' => '#eef2ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-100', 'hex' => '#e0e7ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-200', 'hex' => '#c7d2fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-300', 'hex' => '#a5b4fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-400', 'hex' => '#818cf8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-500', 'hex' => '#6366f1', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-600', 'hex' => '#4f46e5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-700', 'hex' => '#4338ca', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-800', 'hex' => '#3730a3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-indigo-900', 'hex' => '#312e81', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-50', 'hex' => '#f5f3ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-100', 'hex' => '#ede9fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-200', 'hex' => '#ddd6fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-300', 'hex' => '#c4b5fd', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-400', 'hex' => '#a78bfa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-500', 'hex' => '#8b5cf6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-600', 'hex' => '#7c3aed', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-700', 'hex' => '#6d28d9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-800', 'hex' => '#5b21b6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-violet-900', 'hex' => '#4c1d95', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-50', 'hex' => '#faf5ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-100', 'hex' => '#f3e8ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-200', 'hex' => '#e9d5ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-300', 'hex' => '#d8b4fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-400', 'hex' => '#c084fc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-500', 'hex' => '#a855f7', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-600', 'hex' => '#9333ea', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-700', 'hex' => '#7e22ce', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-800', 'hex' => '#6b21a8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-purple-900', 'hex' => '#581c87', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-50', 'hex' => '#fdf4ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-100', 'hex' => '#fae8ff', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-200', 'hex' => '#f5d0fe', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-300', 'hex' => '#f0abfc', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-400', 'hex' => '#e879f9', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-500', 'hex' => '#d946ef', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-600', 'hex' => '#c026d3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-700', 'hex' => '#a21caf', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-800', 'hex' => '#86198f', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-fuchsia-900', 'hex' => '#701a75', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-50', 'hex' => '#fdf2f8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-100', 'hex' => '#fce7f3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-200', 'hex' => '#fbcfe8', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-300', 'hex' => '#f9a8d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-400', 'hex' => '#f472b6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-500', 'hex' => '#ec4899', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-600', 'hex' => '#db2777', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-700', 'hex' => '#be185d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-800', 'hex' => '#9d174d', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-pink-900', 'hex' => '#831843', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-50', 'hex' => '#fff1f2', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-100', 'hex' => '#ffe4e6', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-200', 'hex' => '#fecdd3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-300', 'hex' => '#fda4af', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-400', 'hex' => '#fb7185', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-500', 'hex' => '#f43f5e', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-600', 'hex' => '#e11d48', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-700', 'hex' => '#be123c', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-800', 'hex' => '#9f1239', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-rose-900', 'hex' => '#881337', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-50', 'hex' => '#fafafa', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-100', 'hex' => '#f5f5f5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-200', 'hex' => '#e5e5e5', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-300', 'hex' => '#d4d4d4', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-400', 'hex' => '#a3a3a3', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-500', 'hex' => '#737373', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-600', 'hex' => '#525252', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-700', 'hex' => '#404040', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-800', 'hex' => '#262626', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-true-gray-900', 'hex' => '#171717', 'created_id' => 1, 'created_at' => Carbon::now() ],
            [ 'group' => 'border', 'code' => 'border-DEFAULT', 'hex' => '#e5e7eb', 'created_id' => 1, 'created_at' => Carbon::now() ],
        ]);
    }
}
