<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class m_general_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table(env('TABLE_PREFIX') . 'm_general')->insert([
            [
                'code' => null,
                'group' => 'SELECT TAHUN',
                'key' => null,
                'value_1' => '2022',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT TAHUN',
                'key' => null,
                'value_1' => '2023',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT TAHUN',
                'key' => null,
                'value_1' => '2024',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT TAHUN',
                'key' => null,
                'value_1' => '2025',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],

            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'January',
                'value_2' => '1',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'February',
                'value_2' => '2',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'March',
                'value_2' => '3',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'April',
                'value_2' => '4',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'May',
                'value_2' => '5',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'June',
                'value_2' => '6',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'July',
                'value_2' => '7',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'August',
                'value_2' => '8',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'September',
                'value_2' => '9',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'October',
                'value_2' => '10',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'November',
                'value_2' => '11',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SELECT BULAN',
                'key' => null,
                'value_1' => 'December',
                'value_2' => '12',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'POSITION',
                'key' => null,
                'value_1' => 'RW',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'POSITION',
                'key' => null,
                'value_1' => 'RT',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'POSITION',
                'key' => null,
                'value_1' => 'Admin',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'POSITION',
                'key' => null,
                'value_1' => 'Pengurus',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'KEPERLUAN PENGUNJUNG',
                'key' => null,
                'value_1' => 'Tamu',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE LAPORAN',
                'key' => null,
                'value_1' => 'Aduan Warga',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => false,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE PATROL',
                'key' => null,
                'value_1' => 'RANDOM',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE PATROL',
                'key' => null,
                'value_1' => 'ONE CYCLE',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'SENIN',
                'value_2' => 'Sunday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'SELASA',
                'value_2' => 'Tuesday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'RABU',
                'value_2' => 'Wednesday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'KAMIS',
                'value_2' => 'Thursday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'JUMAT',
                'value_2' => 'Friday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'SABTU',
                'value_2' => 'Saturday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'MINGGU',
                'value_2' => 'Monday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE HARI PATROL',
                'key' => null,
                'value_1' => 'TIAP HARI',
                'value_2' => 'Fullday',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'RADIUS ABSENSI',
                'key' => null,
                'value_1' => '5',
                'value_2' => 'meter',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'RADIUS CHECKIN PATROL',
                'key' => null,
                'value_1' => '5',
                'value_2' => 'meter',
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE KANTOR',
                'key' => null,
                'value_1' => 'Management',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE KANTOR',
                'key' => null,
                'value_1' => 'Security',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'MODULE',
                'key' => null,
                'value_1' => 'Setup',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'MODULE',
                'key' => null,
                'value_1' => 'Security',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SUBMODULE',
                'key' => null,
                'value_1' => 'Master',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'SUBMODULE',
                'key' => null,
                'value_1' => 'Transactions',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],

            [
                'code' => null,
                'group' => 'STACK CATEGORY',
                'key' => null,
                'value_1' => 'Mobile Application',
                'value_2' => 'MB',
                'value_3' => '<i class="fa-light fa-mobile"></i>',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'STACK CATEGORY',
                'key' => null,
                'value_1' => 'Landing Page',
                'value_2' => 'LP',
                'value_3' => '<i class="fa-light fa-house-day"></i>',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'STACK CATEGORY',
                'key' => null,
                'value_1' => 'Backoffice',
                'value_2' => 'BO',
                'value_3' => '<i class="fa-light fa-desktop"></i>',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'STACK CATEGORY',
                'key' => null,
                'value_1' => 'API Service',
                'value_2' => 'API',
                'value_3' => '<i class="fa-light fa-chart-network"></i>',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'BACKLOG STATUS',
                'key' => null,
                'value_1' => 'DRAFT',
                'value_2' => 'bg-gray-100',
                'value_3' => 'text-black',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'BACKLOG STATUS',
                'key' => null,
                'value_1' => 'TODO',
                'value_2' => 'bg-gray-300',
                'value_3' => 'text-black',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'BACKLOG STATUS',
                'key' => null,
                'value_1' => 'NEED REVIEW',
                'value_2' => 'bg-yellow-500',
                'value_3' => 'text-black',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'BACKLOG STATUS',
                'key' => null,
                'value_1' => 'NEED REVISION',
                'value_2' => 'bg-orange-500',
                'value_3' => 'text-white',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'BACKLOG STATUS',
                'key' => null,
                'value_1' => 'NEED UPDATE',
                'value_2' => 'bg-blue-500',
                'value_3' => 'text-white',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'BACKLOG STATUS',
                'key' => null,
                'value_1' => 'COMPLETE',
                'value_2' => 'bg-emerald-400',
                'value_3' => 'text-white',
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE ABSENSI',
                'key' => null,
                'value_1' => 'Sakit',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE ABSENSI',
                'key' => null,
                'value_1' => 'Cuti',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE ABSENSI',
                'key' => null,
                'value_1' => 'Perjalanan Dinas',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE ABSENSI',
                'key' => null,
                'value_1' => 'Lainnya',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE SHIFT',
                'key' => null,
                'value_1' => 'SHIFT PAGI',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE SHIFT',
                'key' => null,
                'value_1' => 'SHIFT SIANG',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE SHIFT',
                'key' => null,
                'value_1' => 'SHIFT SORE',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'code' => null,
                'group' => 'TIPE SHIFT',
                'key' => null,
                'value_1' => 'SHIFT MALAM',
                'value_2' => null,
                'value_3' => null,
                'active_flag' => true,
                'created_id' => 1,
                'updated_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
        ]);
    }
}
